---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lints
    runs-on: ubuntu-latest  # Sử dụng phiên bản Ubuntu ổn định

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Test with Docker Compose
        run: |
          docker-compose up -d  # Khởi động container
          docker-compose run --rm app sh -c "python manage.py test"  # Chạy test
          docker-compose down  # Dừng container sau khi test
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

