---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lints
    runs-on: ubuntu-latest  # Sử dụng phiên bản Ubuntu ổn định

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses:actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"                                                                                                                
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

     

